services:
  - type: web
    name: cloud-storage
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: SERVER_PORT
        value: "8080"
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URL
        sync: false
      - key: YANDEX_CLIENT_ID
        sync: false
      - key: YANDEX_CLIENT_SECRET
        sync: false
      - key: YANDEX_REDIRECT_URL
        sync: false
      - key: VK_CLIENT_ID
        sync: false
      - key: VK_CLIENT_SECRET
        sync: false
      - key: VK_REDIRECT_URL
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: LIBRARY_ADMINS
        sync: false
